---
- name: Install Unbound and BIND system package
  notify: [ "restart named", "restart named" ]
  ansible.builtin.dnf:
    name: [ "unbound", "bind" ]
    state: present

- name: Create zones folder for bind
  ansible.builtin.file:
    path: /var/named/zones
    state: directory
    owner: named
    group: named
    mode: "u=rwx,g=rwx,o="

- name: Template zone for zynthovian.xyz
  notify: [ "restart named" ]
  ansible.builtin.copy:
    content: "{{ lookup('template', 'zynthovian.xyz.j2') }}"
    dest: "/var/named/zones/zynthovian.xyz"
    owner: named
    group: named
    mode: "u=r,g=r,o="

- name: Template BIND configuration
  notify: [ "restart named" ]
  ansible.builtin.copy:
    content: "{{ lookup('template','named.conf.j2') }}"
    dest: "/etc/named.conf"
    owner: root
    group: named
    mode: "u=rw,g=r,o="

- name: Template Unbound configuration
  notify: [ "restart unbound" ]
  ansible.builtin.copy:
    content: "{{ lookup('template','unbound.conf.j2') }}"
    dest: "/etc/unbound/unbound.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
