# Variables for the `arillso.logrotate` galaxy role

logrotate_global_config: false # Only want to control files in includes
logrotate_applications:
  - name: nftables
    definitions:
      - logs:
          - /var/log/nftables.log
        options:
          - rotate 5
          - daily
          - maxsize 100M
          - missingok
          - notifempty
          - delaycompress
          - compress

# Variables for rsyslog task

rsyslog_rsyslog_d_files:
  - name: nftables
    content: |
      :msg, regex, "^nftables\." {
          action(type="omfile" file="/var/log/nftables.log")
          stop
      }
