# Variables for the `arillso.logrotate` galaxy role

logrotate_global_config: false # Only want to control files in includes
logrotate_applications:
  - name: nftables
    definitions:
      - logs:
          - /var/log/nftables.log
          - /var/log/unbound.log
        options:
          - missingok
          - sharedscripts
        postrotate:
          - /usr/bin/systemctl -s HUP kill rsyslog.service >/dev/null 2>&1 || true

# Variables for rsyslog task

rsyslog_rsyslog_d_files:
  - name: nftables
    content: |
      $PreserveFQDN on
      :msg, regex, "^nft\." {
          action(type="omfwd" target="172.21.0.3" port="10514" protocol="tcp")
          action(type="omfile" file="/var/log/nftables.log")
          stop
      }
  - name: unbound
    content: |
      if $programname == 'unbound' then {
          $PreserveFQDN on
          action(type="omfwd" target="172.21.0.3" port="10514" protocol="tcp")
          action(type="omfile" file="/var/log/unbound.log")
          stop
      }
