---
kea_control_agent_config:
    control-sockets:
        d2:
            socket-name: /tmp/kea-ddns-ctrl-socket
            socket-type: unix
        dhcp4:
            socket-name: /tmp/kea4-ctrl-socket
            socket-type: unix
        dhcp6:
            socket-name: /tmp/kea6-ctrl-socket
            socket-type: unix
    http-host: 172.22.0.120
    http-port: 8647
    loggers:
    -   debuglevel: 0
        name: kea-ctrl-agent
        output_options:
        -   flush: true
            maxsize: 204800
            maxver: 4
            output: /var/log/kea-ctrl-agent.log
        severity: INFO

kea_ddns_config: {}

kea_dhcp6_config:
    control-socket:
        socket-name: /tmp/kea6-ctrl-socket
        socket-type: unix
    interfaces-config:
        interfaces:
            - vm-br-vl10
            - vm-br-vl20
    lease-database:
        type: memfile
    loggers:
    -   debuglevel: 0
        name: kea-dhcp6
        output_options:
        -   maxsize: 2048000
            maxver: 4
            output: /var/log/kea-dhcp6.log
        severity: INFO
    rebind-timer: 32400
    renew-timer: 21600
    host-reservation-identifiers:
        - hw-address
        - duid
    mac-sources:
        - duid
        - ipv6-link-local
    subnet6:
    -   interface: vm-br-vl10 #    fd4e:df98:5835:4f08::/64
        subnet: "fd4e:df98:5835:4f08::/64"
        #pools:
        #-   pool: "fd4e:df98:5835:4f08::1-fd4e:df98:5835:4f08:ffff:ffff:ffff:fffe"
        option-data:
        -   name: dns-servers
            data: "fd4e:df98:5835:4f08:9a54:2bf5:27f6:c855"
    -   interface: vm-br-vl20
        subnet: "fd4e:df98:5835:25c2::/64"
        option-data:
        -   name: dns-servers
            data: "fd4e:df98:5835:25c2:5792:4069:a2eb:5aee"


#    Supernet        fd4e:df98:5835:0000:0000:0000:0000:0000/64
#    Subnet-vl10     fd4e:df98:5835:4f08:0000:0000:0000:0000/64
#      vm-br-vl10    fd4e:df98:5835:4f08:9a54:2bf5:27f6:c855/64
#    Subnet-vl20     fd4e:df98:5835:25c2:0000:0000:0000:0000/64
#      vm-br-vl20    fd4e:df98:5835:25c2:5792:4069:a2eb:5aee/64
#    Subnet-vl30     fd4e:df98:5835:5a0f::/64
#    Subnet-vl40     fd4e:df98:5835:0806::/64


# [ 2412.431081] IPv6: enp5s0: IPv6 duplicate address fd4e:df98:5835:25c2:: used by 3c:ec:ef:41:70:c3 detected!
# [ 2438.148866] ixgbe 0000:05:00.0 enp5s0: entered promiscuous mode
# [ 2447.341185] IPv6: enp5s0: IPv6 duplicate address fd4e:df98:5835:25c2:: used by 3c:ec:ef:41:70:c3 detected!
# [ 2569.162024] IPv6: enp5s0: IPv6 duplicate address fd4e:df98:5835:25c2:: used by 3c:ec:ef:41:70:c3 detected!
# [ 2643.376091] IPv6: enp5s0: IPv6 duplicate address fd4e:df98:5835:25c2:: used by 3c:ec:ef:41:70:c3 detected!
# [ 2940.744181] IPv6: enp5s0: IPv6 duplicate address fd4e:df98:5835:25c2:: used by 3c:ec:ef:41:70:c3 detected!
# [ 3457.018351] IPv6: enp5s0: IPv6 duplicate address fd4e:df98:5835:25c2:: used by 3c:ec:ef:41:70:c3 detected!
# [ 3542.484529] ixgbe 0000:05:00.0 enp5s0: left promiscuous mode
# [ 3542.946035] ixgbe 0000:05:00.0 enp5s0: entered promiscuous mode
# [ 3555.183729] IPv6: enp5s0: IPv6 duplicate address fd4e:df98:5835:25c2:: used by 3c:ec:ef:41:70:c3 detected!
# [ 3586.346728] ixgbe 0000:05:00.0 enp5s0: left promiscuous mode
# [ 3600.092128] ixgbe 0000:05:00.0 enp5s0: entered promiscuous mode
# [ 3612.634158] IPv6: enp5s0: IPv6 duplicate address fd4e:df98:5835:25c2:: used by 3c:ec:ef:41:70:c3 detected!
# [ 3641.941245] ixgbe 0000:05:00.0 enp5s0: left promiscuous mode


kea_dhcp4_config:
    control-socket:
        socket-name: /tmp/kea4-ctrl-socket
        socket-type: unix
    expired-leases-processing:
        hold-reclaimed-time: 172800
        max-reclaim-leases: 0
        max-reclaim-time: 0
        reclaim-timer-wait-time: 3600
    hooks-libraries:
    -   library: /usr/lib64/kea/hooks/libdhcp_lease_cmds.so
    -   library: /usr/lib64/kea/hooks/libdhcp_ha.so
        parameters:
            high-availability:
            -   heartbeat-delay: 10000
                max-ack-delay: 5000
                max-response-delay: 30000
                max-unacked-clients: 2
                mode: load-balancing
                peers:
                -   auto-failover: true
                    name: nftfw-5019d
                    role: primary
                    url: http://172.22.0.120:8080/
                -   auto-failover: true
                    name: nftfw-rpiedge
                    role: secondary
                    url: http://172.22.0.119:8080/
                sync-timeout: 60000
                this-server-name: nftfw-5019d
    interfaces-config:
        interfaces:
            - vm-br-vl10
            - vm-br-vl20
    lease-database:
        type: memfile
    loggers:
    -   debuglevel: 0
        name: kea-dhcp4
        output_options:
        -   maxsize: 2048000
            maxver: 4
            output: /var/log/kea-dhcp4.log
        severity: INFO
    rebind-timer: 32400
    renew-timer: 21600
    valid-lifetime: 43200
    subnet4:
    -   interface: vm-br-vl10
        option-data:
        -   data: 172.22.0.1
            name: routers
        -   data: 172.22.0.1
            name: domain-name-servers
        pools:
        -   pool: 172.22.0.20-172.22.0.99
        reservations:
        -   hostname: 5019d-ipmi.man.zynthovian.xyz
            hw-address: 3c:ec:ef:41:7c:be
            ip-address: 172.22.0.3
        -   hostname: xenia.man.zynthovian.xyz
            hw-address: e4:5f:01:24:c8:30
            ip-address: 172.22.0.4
        -   hostname: uap-737652.man.zynthovian.xyz
            hw-address: e0:63:da:73:76:52
            ip-address: 172.22.0.5
        -   hostname: amd64-server-b5915c.man.zynthovian.xyz
            hw-address: b8:85:84:b5:91:5c
            ip-address: 172.22.0.10
        -   hostname: amd64-server-7f97c6.man.zynthovian.xyz
            hw-address: d8:9e:f3:7f:97:c6
            ip-address: 172.22.0.11
        -   hostname: amd64-server-a2e7bb.man.zynthovian.xyz
            hw-address: b8:85:84:a2:e7:bb
            ip-address: 172.22.0.12
        subnet: 172.22.0.0/25
    -   interface: vm-br-vl20
        option-data:
        -   data: 172.22.1.1
            name: routers
        -   data: 172.22.1.1
            name: domain-name-servers
        pools:
        -   pool: 172.22.1.10-172.22.1.110
        reservations:
        -   hostname: 5019d-ipmi.man.zynthovian.xyz
            hw-address: 3c:ec:ef:41:7c:be
            ip-address: 172.22.1.3
        -   hostname: elp-workstation.lan.zynthovian.xyz
            hw-address: 98:B7:85:00:97:E1
            ip-address: 172.22.1.5
        subnet: 172.22.1.0/25
    valid-lifetime: 43200
