- name: Restart BIND
  ansible.builtin.service:
    name: named
    state: restarted
    enabled: true
  become: true
  listen: "restart named"

- name: Restart Unboundd
  ansible.builtin.service:
    name: unbound
    state: restarted
    enabled: true
  become: true
  listen: "restart unbound"
