- name: "[Firewall] Configure host as a firewall"
  hosts: firewall
  become: true
  gather_facts: true
  any_errors_fatal: true

  roles:
    - role: nftables
    - role: fail2ban

  pre_tasks:
    - name: Add nftables configuration to variable
      ansible.builtin.set_fact:
        nftables_rules_raw:
          "{{ lookup('template', 'nftables/main.nft') }}"

  post_tasks:

    - name: Configure rsyslog to intercept nftables kernel logs
      block:
        - name: Deploy rsyslog configuration files
          loop: "{{ rsyslog_rsyslog_d_files }}"
          notify: "Restart Rsyslog"
          ansible.builtin.copy:
            content: "{{ item.content }}"
            dest: /etc/rsyslog.d/{{ item.name }}.conf
            owner: root
            group: root
            mode: u=rw,g=r,o=
        - name: Append rsyslog config files to controlled_files list
          loop: "{{ rsyslog_rsyslog_d_files }}"
          ansible.builtin.set_fact:
            controlled_files: "{{ (controlled_files | default([])) + ['/etc/rsyslog.d/'+item.name+'.conf'] }}"

    - name: Retreive Configuration files from host for tracking
      block:
        - name: Fetch configuration files
          loop: "{{ controlled_files }}"
          when: controlled_files is defined
          ansible.builtin.fetch:
            fail_on_missing: false
            src: "{{ item }}"
            dest: /tmp/config/

  handlers:
    - name: Restart Rsyslog
      ansible.builtin.service:
        name: rsyslog.service
        state: restarted
