
- name: "[Firewall] Configure additional firewall features"
  hosts: firewall
  become: true
  gather_facts: true
  any_errors_fatal: true

  roles:
    - role: linux-system-roles.nbde_server
    - role: geerlingguy.node_exporter
    - role: arillso.logrotate
    - role: keepalived
    - role: haproxy
