kubernetes_dns_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66616537323333353635353763306138306532353663663338643730323864383839373363643932
  6332306639313133373762646133346633636237393534350a363637336239343737656237653631
  66376663663432623865616331666639643731653761303336393930303136353634663034343463
  3862613964303663360a326239323064333835346366663735306633383761346639643664346638
  37643436336632623965343135633064636330303564396563653763656531366332303138643265
  6234363737386533633562616364343731633834376335333966

nsd_server_options_files:
  - name: ansible-server
    content: |
      ip-transparent: yes
      ip-freebind: yes
      reuseport: yes
      #verbosity: 1
      port: 5053

__nsd_allowed_acl:
  - 127.0.0.1/32
  - 172.22.0.10/32
  - 172.22.0.11/32
  - 172.22.0.12/32

nsd_options_files:
  - name: zynthovian-xyz
    content: |
      key:
        name: kubernetes
        algorithm: hmac-sha256
        secret: "{{ kubernetes_dns_key }}"
      zone:
        name: zynthovian.xyz
        zonefile: zynthovian-xyz.zone
        {% for i in __nsd_allowed_acl %}
        allow-notify: {{ i }} kubernetes
        provide-xfr: {{ i }} kubernetes
        {% endfor %}

nsd_zone_files:
  - name: zynthovian-xyz
    zonename: zynthovian.xyz.
    content: |
      $ORIGIN .
      $TTL 30
      zynthovian.xyz          IN SOA  ns.zynthovian.xyz. elliana.perry.gmail.com. (
                                      2023060878 ; serial
                                      300        ; refresh (5 minutes)
                                      3600       ; retry (1 hour)
                                      604800     ; expire (1 week)
                                      300        ; minimum (5 minutes)
                                      )
                              NS      ns.zynthovian.xyz.
      $ORIGIN zynthovian.xyz.
      $TTL 30
      ingress                 A       172.21.0.1
      ns                      A       172.22.0.1
                              A       172.22.1.1
                              A       172.22.0.120
                              A       172.22.0.21
      amd64-server-7f97c6     A       172.22.0.11
      amd64-server-a2e7bb     A       172.22.0.12
      amd64-server-b5915c     A       172.22.0.10
      xenia                   A       172.22.0.20
      minio                   A       172.22.0.20
      legion                  A       172.22.1.5
      palworld                A       172.22.0.21
      nftfw-a                 A       172.22.0.120
                              A       172.22.1.120
      nftfw-b                 A       172.22.0.121
                              A       172.22.1.121
      $ORIGIN int.zynthovian.xyz.
      $TTL 30
      ingress                 A       172.21.0.1
      ns                      A       172.22.0.1
                              A       172.22.1.1
                              A       172.22.0.120
      amd64-server-7f97c6     A       172.22.0.11
      amd64-server-a2e7bb     A       172.22.0.12
      amd64-server-b5915c     A       172.22.0.10
      xenia                   A       172.22.0.20
      minio                   A       172.22.0.20
      nftfw-a                 A       172.22.0.120
                              A       172.22.1.120
      nftfw-b                 A       172.22.0.121
                              A       172.22.1.121
      ; end of file (nsd-checkzone fails without this?)

unbound_config_d:
  - name: server-config.conf
    content: |
      server:
        chroot: ""
        # Configure interfaces
        ip-freebind: yes
        #interface: 0.0.0.0
        # Configure ACLs
        access-control: 0.0.0.0/0 allow

        # Allow querying the localhost
        do-not-query-localhost: no

        # Configure trust anchor and root hints
        #auto-trust-anchor-file: "/var/lib/unbound/root.key"
        #root-hints: "/var/lib/unbound/root.hints"
        module-config: "validator iterator"
        #verbosity: 3

        log-queries: yes
        log-replies: yes
  - name: local-fwd-zone.conf
    content: |
      # This is disgusting and in no way preferable
      #   But most importantly - It works
      forward-zone:
        name: "ipv4.zynthovian.xyz"
        forward-addr: 1.1.1.1
        forward-addr: 8.8.8.8
      forward-zone:
        name: "vpn.zynthovian.xyz"
        forward-addr: 1.1.1.1
        forward-addr: 8.8.8.8
      forward-zone:
        name: "_acme-challenge.zynthovian.xyz"
        forward-addr: 1.1.1.1
        forward-addr: 8.8.8.8
      forward-zone:
        name: "zynthovian.xyz"
        forward-addr: 127.0.0.1@2053
  - name: inet-fwd-zone.conf
    content: |
        forward-zone:
          name: "."
          forward-addr: 1.1.1.1
          forward-addr: 8.8.8.8
  - name: ar51an-unbound.conf
    content: |
      server:
        # |Buffers|
        # EDNS reassembly buffer to advertise to UDP peers (the actual buffer
        # is set with msg-buffer-size)
        edns-buffer-size: 1232
        # Increase incoming and outgoing query buffer size to cover traffic peaks
        so-rcvbuf: 4m
        so-sndbuf: 4m

        # |Cache|
        # Slabs reduce lock contention by threads. Set to power of 2, close to num-threads
        msg-cache-slabs: 8
        rrset-cache-slabs: 8
        infra-cache-slabs: 8
        key-cache-slabs: 8
        # rrset-cache-size should be twice of msg-cache-size
        msg-cache-size: 64m
        rrset-cache-size: 128m
        # Time to live minimum for messages in cache. More than an hour could easily
        # give trouble due to stale data. Default is 0
        cache-min-ttl: 0
        cache-max-ttl: 86400
        # Number of bytes size of the aggressive negative cache
        neg-cache-size: 4m
        # Perform prefetching of almost expired message cache entrie
        prefetch: yes
        # Fetch the DNSKEYs earlier in the validation process, when a DS record is
        # encountered. This lowers the latency of requests at the expense of little
        # more CPU usage.
        prefetch-key: yes
        # Have unbound attempt to serve old responses from cache with a TTL of 0 in
        # the response without waiting for the actual resolution to finish. The
        # actual resolution answer ends up in the cache later on.
        serve-expired: yes
        # TTL value to use when replying with expired data. If serve-expired-client-timeout
        # is used then recommended to use 30. Default is 30
        # Added for cachedb warning at unbound start. Unbound sets it to 0 for records
        # originating from cachedb
        serve-expired-reply-ttl: 0

        # |Hardening|
        # Trust glue only if it is within the servers authority
        harden-glue: yes
        # Ignore very large queries.
        harden-large-queries: yes
        # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes bogus
        # To disable DNSSEC, set harden-dnssec stripped: no
        harden-dnssec-stripped: yes
        # Harden against algorithm downgrade when multiple algorithms are advertised in the DS record
        harden-algo-downgrade: yes
        # Ignore very small EDNS buffer sizes from queries.
        harden-short-bufsize: yes

        # |Logging|
        # Verbosity: Default is 1
        # 0 No verbosity, only errors
        # 1 Operational information
        # 2 Detailed operational information
        # 3 Query level information, output per query
        # 4 Algorithm level information
        # 5 Client identification for cache misses
        verbosity: 0
        # Prints one line per query to the log
        log-queries: no
        # Prints one line per reply to the log
        log-replies: no
        # Print log lines that say why queries return SERVFAIL to clients
        log-servfail: no
        # Print log lines to inform about local zone actions. Shows blocked domains
        log-local-actions: no
        # If this option is given, the use-syslog is option is set to "no"
        #logfile: /dev/null

        # |Privacy|
        # Deny queries of type ANY with an empty response
        deny-any: yes
        # Set the total number of unwanted replies to keep track of in every thread.
        # If it reaches the threshold, warning is printed and a defensive action is
        # taken, cache is cleared to flush away any poison
        # Suggested value is 10000000, default is 0 (turned off)
        unwanted-reply-threshold: 10000
        # Rotates RRSet order in response (the pseudo-random number is taken from
        # the query ID, for speed and thread safety)
        rrset-roundrobin: yes
        # Send minimum amount of information to upstream servers to enhance privacy
        qname-minimisation: yes
        # Do no insert authority/additional sections into response messages when
        # those sections are not required. This reduces response size significantly
        # and may avoid TCP fallback for some responses. It may speedup slightly.
        minimal-responses: yes
        # Refuse id.server and hostname.bind queries
        hide-identity: yes
        # Report this identity rather than the hostname of the server.
        identity: "DNS"
        # Refuse version.server and version.bind queries
        hide-version: yes
        # Control which clients are allowed to make (recursive) queries to this
        # server. By default everything is refused, except for localhost
        access-control: 127.0.0.0/8 allow
        access-control: 10.1.1.0/24 allow
        # Enforce privacy of these addresses. Strips them away from answers.
        # It may cause DNSSEC validation to additionally mark it as bogus.
        # Protects against DNS Rebinding
        private-address: 10.1.1.0/24
  - name: ar51an-redis-cache.conf
    state: absent # ! cachedb needs compiled in
    content: |
      server:
        module-config: "validator cachedb iterator"
      cachedb:
        backend: redis
        secret-seed: "unbound"

        # |Redis|
        # IP address of redis server. Default is 127.0.0.1
        redis-server-host: 127.0.0.1
        # TCP port number of redis server. Default is 6379
        redis-server-port: 6379
        # Period until unbound waits for response from redis sever. Default is 100ms
        redis-timeout: 100
        # Redis record expiration. If yes, unbound sets timeout for redis records so
        # that redis can evict expired keys automatically. If unbound is configured
        # with serve-expired this option internally reverts to no. Default is no
        redis-expire-records: no

# unbound_blocklist_url: "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts"
unbound_blocklist_url: "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts"
